export enum WindowAnimationState {
    OPENING = 'OPENING',
    CLOSING = 'CLOSING',
    MINIMIZING = 'MINIMIZING',
    MINIMIZED = 'MINIMIZED',
    RESTORING = 'RESTORING',
    VISIBLE = 'VISIBLE',
    DRAGGING = 'DRAGGING',
    RESIZING = 'RESIZING',
}